### ISSUE TITLE
named_textfield

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#100]
Given a textfield with an accessibility identifier:

`[myTextField setAccessibilityIdentifier:@"my_unique_name_for_this_textfield"];`

It appears twice in the page output:

```
UIATableCell
   name: my_unique_name_for_this_textfield
  value: 
UIATextField
   name: my_unique_name_for_this_textfield
  label: 
  value:
```

`name('my_unique_name_for_this_textfield').type` will type into the table cell instead of the textfield.

``` ruby
def named_textfield target_name
  wait do
    target = e_textfields.detect { |e| e.name == target_name }
    raise 'name textfiled not found' unless target
    target
  end
end
```

Now we know the proper type has been selected.

``` ruby
named_textfield('woven_account_name_textfield').type 'testing'
```
